### ISSUE TITLE
Pruning generates traceback on interface objects

### ISSUE THREAD

**Issue by synackray** [synackray/vcenter-netbox-sync#24]
### Environment
* Python version:  3.6.8
* NetBox version: 2.6.11
* vCenter version: 6.7.0
* vCenter NetBox Sync version:  1.0.0-rc.3

### Steps to Reproduce
1. Execute `run.py` and allow sync to complete
2. Delete interface object from a virtual machine within vCenter
3. Modify `settings.py` variable `NB_PRUNE_ENABLED` to `True`.
4. Execute `run.py` again.

### Expected Behavior
The deleted interface will be marked as orphaned and if it surpasses the `NB_PRUNE_DELAY_DAYS` variable it will be deleted.

### Observed Behavior
A traceback is generated. 
```
2020-01-05 05:43:02,490 [INFO] Processing orphaned NetBox virtual_interfaces 'vNIC6' object.
Traceback (most recent call last):
  File "run.py", line 1221, in <module>
    main()
  File "run.py", line 49, in main
    nb.sync_objects(vc_obj_type="virtual_machines")
  File "run.py", line 948, in sync_objects
    self.prune_objects(vc_objects, vc_obj_type)
  File "run.py", line 1046, in prune_objects
    int(orphan["last_updated"][:4]), # Year
KeyError: 'last_updated'
```

**Comment by synackray** [comment]
Reviewing the KeyError the `last_updated` field does not exist in the `/dcim/interfaces/{id}` or `/virtualization/interfaces/{id}` object models. I [posted](https://groups.google.com/forum/#!topic/netbox-discuss/WfVheuSm_4Q) this to the NetBox discussion list to see if this is version specific or a generic as well as whether this is desired behavior. 

In the meantime I will create a workaround for it.

**Comment by synackray** [comment]
Running commits through manual testing before moving to `develop` branch
